name: imgui_binder
description: A sample command-line application.
version: 1.0.0
publish_to: 'none'

environment:
  sdk: ^3.6.1

dependencies:
  dart_style: ^2.3.7
  endec:
    git:
      url: https://github.com/gliscowo/endec.dart
      ref: 0397d48
  endec_json:
    git:
      url: https://github.com/gliscowo/endec.dart
      ref: 0397d48
      path: endec_json

dependency_overrides:
  endec:
    git:
      url: https://github.com/gliscowo/endec.dart
      ref: 0397d48

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
  endec_builder:
    git:
      url: https://github.com/gliscowo/endec.dart
      ref: 0397d48
      path: endec_builder
  build_runner: ^2.4.14
